export const surpriseMePrompts = [
    "A futuristic cityscape at dusk",
    "A magical forest with glowing mushrooms",
    "An underwater adventure with colorful marine life",
    "A steampunk-inspired flying machine",
    "A serene mountain landscape with a flowing waterfall",
    "An alien marketplace on a distant planet",
    "A whimsical tea party with talking animals",
    "A time-traveling explorer encountering dinosaurs",
    "A cyberpunk street scene with neon lights",
    "A floating island with gravity-defying architecture",
    "A dramatic space battle between starships",
    "A haunted mansion shrouded in mist",
    "A peaceful countryside with rolling hills and grazing sheep",
    "A bustling market in a Moroccan-inspired city",
    "A journey through a wormhole to another dimension",
    "A hidden cave filled with sparkling crystals",
    "A futuristic sports arena with high-tech equipment",
    "A group of adventurers riding mythical creatures",
    "A post-apocalyptic landscape reclaimed by nature",
    "A masquerade ball in an opulent Venetian palace",
    "An ancient temple in the heart of the jungle",
    "A floating city above the clouds",
    "A tranquil lakeside cabin under the stars",
    "A space colony on a distant exoplanet",
    "A surreal landscape where land and sea merge",
    "A caravan crossing a vast desert with sand dunes",
    "An enchanted library with books that come to life",
    "A grand steampunk-inspired train traveling through a canyon",
    "A futuristic laboratory conducting experiments",
    "A whimsical carousel with mythical creatures as rides",
    "A city inhabited by humanoid animals",
    "A Viking ship navigating through icy waters",
    "A hidden garden with plants that emit soft light",
    "A gladiator arena in ancient Rome",
    "A floating waterfall on an alien moon",
    "A space station orbiting a distant planet",
    "A snowy village with colorful houses",
    "An underwater city with transparent domes",
    "A medieval castle perched on a cliff",
    "A dance party with robots and humans",
    "A tropical island with bioluminescent beaches",
    "A time-traveler meeting their future self",
    "A hidden steampunk city beneath the surface",
    "A futuristic subway system with levitating trains",
    "A coral reef city with merfolk and marine creatures",
    "A wizard's tower surrounded by magical creatures",
    "An ancient colosseum hosting a mythical beast battle",
    "A cityscape in a world where gravity works sideways",
    "A floating garden in the sky with flying flora",
    "A high-speed race through a neon-lit canyon",
    "A space explorer encountering an ancient alien civilization",
    "A pirate ship sailing through a stormy sea",
    "A lunar base with astronauts and advanced technology",
    "A tribal village in a lush rainforest",
    "A journey through a virtual reality wonderland",
    "An enchanted desert with sand that shimmers like gold",
    "A hidden city within a massive crystal cavern",
    "A colony on Mars with terraformed landscapes",
    "A labyrinthine library filled with endless books",
    "A massive treehouse village in a giant tree",
    "A concert of music played by creatures from different planets",
    "A futuristic city where nature and technology coexist",
    "An archaeological dig site with ancient artifacts",
    "A coastal town in a world of perpetual sunset",
    "A cosmic circus with performers from across the universe",
    "A serene zen garden with intricate stone arrangements",
    "An intergalactic marketplace with traders from various species",
    "A parallel dimension where reality shifts and bends",
    "A snow-covered city with steam-powered vehicles",
    "An underwater archaeological site with sunken ruins",
    "A factory where clouds are harvested and bottled",
    "A glacial ice cave with mesmerizing ice formations",
    "A city powered by renewable energy sources",
    "A secret garden hidden behind a waterfall",
    "An ancient observatory with celestial wonders",
    "A society of sentient robots building their own civilization",
    "A world where everyday objects possess magical abilities",
    "A rainforest with bioluminescent flora and fauna",
    "An interstellar train traveling through wormholes",
    "A city where art and creativity are the primary currency",
    "An oasis in the middle of a vast desert",
    "A futuristic amusement park with gravity-defying rides",
    "A sunken city beneath a calm and mysterious ocean",
    "A community of treehouse dwellers in an enchanted forest",
    "A floating city powered by giant helium balloons",
    "An alien desert with towering crystalline rock formations",
    "A hidden realm accessible only through ancient doorways",
    "A society living within the hollowed-out interior of a planet",
    "A cityscape with buildings made of living, organic material",
    "An otherworldly carnival with bizarre attractions",
    "A realm where dreams come to life as floating islands",
    "A castle carved into the side of a colossal waterfall",
    "A futuristic farm where holographic crops are grown",
    "A world where the sun never sets, in perpetual daylight",
    "A mechanical forest filled with clockwork animals",
    "An abandoned space station slowly being reclaimed by nature",
    "A town where mythical creatures live in harmony with humans",
    "A fantastical library with books that reveal the reader's destiny",
    "A colony on an asteroid with sprawling biodomes",
    "A city of living crystals with colorful light displays",
    "A journey through a realm of abstract geometric landscapes",
    "A floating village on the back of a colossal flying creature",
    "An ancient tree with doors leading to different realms",
    "A futuristic city where transportation is through teleportation",
    "A society that communicates through patterns of light and color",
    "A labyrinthine market filled with exotic goods from across the universe",
    "An island paradise with sentient plant life and talking animals",
    "A spacefaring civilization in the midst of cosmic migration",
    "A hidden city beneath the surface, illuminated by bioluminescence",
    "A jungle with plants that emit musical tones when touched",
    "A city inhabited by miniature people living in oversized plants",
    "A surreal land of floating islands and upside-down landscapes",
    "An underwater metropolis with transparent tunnels",
    "A realm of mirrors where reflections come to life",
    "A space colony with architecture inspired by ancient civilizations",
    "A city of the future with transportation networks woven into the skyline",
    "A fantastical train station connecting different realms",
    "A realm where imagination is a tangible force shaping reality",
    "A city surrounded by massive crystalline formations",
    "An arctic research station in a world of eternal winter",
    "A hidden valley filled with mythical creatures",
    "A cosmic library with books containing the knowledge of the universe",
    "A sky city built on levitating platforms",
    "A society that uses music to cast spells and perform magic",
    "An abandoned theme park with eerie and overgrown attractions",
    "A world where gravity changes direction at random intervals",
    "A city of architects who shape reality through their drawings",
    "A realm of floating temples and ancient mysticism",
    "An enchanted carnival that appears only under a full moon",
    "A forest where trees communicate through patterns of light",
    "A space settlement built within the ruins of an ancient spaceship",
    "A city where the buildings are made of giant crystals",
    "An underwater world with glowing flora and fauna",
    "A realm where thoughts manifest as tangible objects",
    "A futuristic city with transportation via energy bridges",
    "A society that lives among the clouds in dirigible cities",
    "An ancient labyrinth with shifting walls and illusions",
    "A desert with sand that turns into precious gems at night",
    "A colony on a planet with colorful, bioluminescent landscapes",
    "A city where architecture defies the laws of physics",
    "A surreal desert with gravity-defying rock formations",
    "An underwater garden with sculptures made of coral and shells",
    "A land of perpetual twilight with luminescent wildlife",
    "A society that harnesses the power of dreams for energy",
    "An overgrown city with plant life reclaiming the urban landscape",
    "A realm of floating castles and sky knights",
    "A world where the boundary between reality and illusion is blurred",
    "An ancient city hidden within the heart of a massive tree",
    "A futuristic metropolis with holographic billboards and AI assistants",
    "A civilization that lives within the hollowed-out remains of a giant creature",
    "A city where every building is a giant, elaborate clock",
    "An underwater civilization with elegant merfolk and intricate architecture",
    "A realm where animals have evolved to possess human-like traits",
    "A space colony on a planet orbiting a binary star system",
    "A forest of giant mushrooms with bioluminescent caps",
    "A cityscape where gravity is optional, and people can walk on any surface",
    "An abandoned alien theme park with remnants of its former glory",
    "A world where day and night exist simultaneously in different regions",
    "A society that travels on the backs of colossal, roaming creatures",
    "A city of living machines with personalities and emotions",
    "An underwater realm with towering kelp forests and vibrant marine life",
    "A realm where colors have magical properties and can be woven into spells",
    "A futuristic city with buildings that shift and adapt to the environment",
    "An ancient library filled with books containing the memories of past readers",
    "A society of skydivers living on floating islands amidst the clouds",
    "A realm of eternal autumn with leaves that emit a soft, warm light",
    "A city where people communicate through intricate, choreographed dances",
    "An abandoned space colony with remnants of advanced technology",
    "A world where mythical creatures exist, hidden from human sight",
    "A civilization that lives within the roots of a colossal tree",
    "An underwater realm with bioluminescent constellations",
    "A realm where the landscapes are composed of living, breathing organisms",
    "A city where architecture is inspired by optical illusions and impossible geometry",
    "An ancient civilization living in harmony with sentient crystal beings",
    "A society that travels in massive airships, drifting through the skies",
    "A realm where emotions are visible as colorful auras surrounding people",
    "A city of interconnected treehouses and suspension bridges",
    "An underwater city with transportation through giant bubbles",
    "A futuristic city with towering skyscrapers covered in vertical gardens",
    "A realm of floating islands held aloft by massive floating creatures",
    "A world where the boundary between dreams and reality is fluid",
    "A society that communicates through a complex language of gestures and symbols",
    "An ancient city with architecture carved into the sides of massive cliffs",
    "A realm where music has the power to shape landscapes and environments",
    "A city of artists who paint with light and create living artworks",
    "An underwater realm with bioluminescent rain that falls upward",
    "A futuristic metropolis with holographic pathways and interactive displays",
    "A world where the seasons shift unpredictably and rapidly",
    "A society that lives within immense, mobile tree cities",
    "A realm where the terrain is made of shifting, colorful sand dunes",
    "A city where transportation is through giant, rideable insects",
    "An ancient civilization that has mastered control over time",
    "A realm where spoken words transform into physical objects",
    "A world with floating islands made of enchanted crystal formations",
    "A society of skywalkers who traverse mountain ranges on tightropes",
    "A city within the hollowed-out remains of an ancient giant statue",
    "An underwater civilization with architecture made from living corals",
    "A realm where weather patterns are influenced by the collective emotions of the populace",
    "A city of architects who design structures that shift and change shape",
    "An ancient city with streets paved with precious gemstones",
    "A world where plants possess consciousness and communicate with humans",
    "A society that communicates through intricate patterns of wind chimes",
    "A realm where the landscape is constantly shifting and morphing",
    "A city where inhabitants can control the weather through rituals",
    "An underwater realm with bioluminescent caves and hidden treasures",
    "A futuristic metropolis with transportation through pneumatic tubes",
    "A world where gravity varies depending on the time of day",
    "A society that communicates through a language of scents and aromas",
    "An ancient city built within the branches of a colossal ancient tree",
    "A realm of floating mountains and cascading waterfalls in the sky",
    "A city where buildings are constructed from living, genetically-engineered organisms",
    "An underwater civilization with technology powered by harnessing ocean currents",
    "A society that communicates through intricate patterns of light and shadow",
    "A realm where the boundaries between the physical and spiritual worlds are blurred",
    "A city with architecture that changes color based on the emotions of the populace",
    "An ancient city hidden beneath the sands of a vast desert",
    "A world where animals possess the ability to manipulate natural elements",
    "A society that communicates through the movement of celestial bodies",
    "A realm where dreams and nightmares manifest as tangible entities",
    "A city built on the back of a colossal, ancient creature",
    "An underwater realm with cities enclosed in air bubbles on the ocean floor",
    "A futuristic metropolis with transportation through personal teleportation devices",
    "A world where flora and fauna emit soft melodies as they interact",
    "A society that communicates through the arrangement of living plants",
    "An ancient city with architecture shaped by ancient cosmic alignments",
    "A realm of floating gardens with plants that defy gravity",
    "A city where people communicate through intricate, synchronized movements",
    "An underwater civilization with technology powered by harnessing bioluminescence",
    "A society that communicates through the patterns of water ripples",
    "A realm where time and space are malleable, controlled by the inhabitants",
    "A city with architecture that shifts and transforms based on the phases of the moon",
    "An ancient city hidden within the depths of a vast, unexplored forest",
    "A world where animals possess the ability to manipulate the weather",
    "A society that communicates through the patterns of celestial events",
    "A realm where dreams are interconnected, forming a collective dreamworld",
    "A city built on the back of a massive, ancient creature that roams the land",
    "An underwater realm with cities nestled within giant underwater caves",
    "A futuristic metropolis with transportation through personal anti-gravity devices",
    "A world where flora and fauna emit vibrant colors as they interact",
    "A society that communicates through the arrangement of stones and crystals",
    "An ancient city with architecture influenced by the positions of stars",
    "A realm of floating waterfalls and rivers suspended in mid-air",
    "A city where inhabitants communicate through telepathic connections",
    "An underwater civilization with technology powered by harnessing thermal vents",
    "A society that communicates through the patterns of lightning storms",
    "A realm where the boundaries between dimensions are thin and easily traversable",
    "A city with architecture that interacts with the natural energy currents of the earth",
    "An ancient city hidden within the heart of an expansive, ancient cave system",
    "A world where animals possess the ability to manipulate plant growth",
    "A society that communicates through the arrangement of clouds in the sky",
    "A realm where emotions and thoughts manifest as physical entities",
    "A city built on the back of a colossal, ancient aquatic creature",
    "An underwater realm with cities within gigantic coral formations",
    "A futuristic metropolis with transportation through personal holographic pods",
    "A world where flora and fauna emit harmonious musical tones as they interact",
    "A society that communicates through the arrangement of snowflakes",
    "An ancient city with architecture influenced by the phases of the planets",
    "A realm of floating islands with waterfalls that flow upwards",
    "A city where inhabitants communicate through the manipulation of fire",
    "An underwater civilization with technology powered by harnessing underwater geysers",
    "A society that communicates through the patterns of migrating birds",
    "A realm where dreams and reality merge, creating a constantly shifting existence",
    "A city with architecture that adapts to the energy flows of the earth",
    "An ancient city hidden within the intricate network of an underground cave system",
    "A world where animals possess the ability to communicate with humans through images",
    "A society that communicates through the arrangement of sand dunes in the desert",
    "A realm where thoughts become visible as shimmering, colorful threads",
    "A city built on the back of a colossal, ancient bird-like creature",
    "An underwater realm with cities suspended within giant floating bubbles",
    "A futuristic metropolis with transportation through personal teleportation rings",
    "A world where flora and fauna emit intricate patterns of light as they interact",
    "A society that communicates through the arrangement of leaves on trees",
    "An ancient city with architecture influenced by the phases of the moons",
    "A realm of floating islands with rivers that flow in mid-air",
    "A city where inhabitants communicate through the movement of shadows",
    "An underwater civilization with technology powered by harnessing tidal forces",
    "A society that communicates through the patterns of migrating fish",
    "A realm where dreams shape the physical environment, creating a dream-like reality",
    "A city with architecture that responds to the vibrations of the earth",
    "An ancient city hidden within the labyrinthine tunnels of an ancient cave system",
    "A world where animals possess the ability to manipulate the growth of plants",
    "A society that communicates through the arrangement of clouds in the sky",
    "A realm where emotions and thoughts manifest as visible, swirling energy",
    "A city built on the back of a colossal, ancient serpent-like creature",
    "An underwater realm with cities nestled within intricate underwater caves",
    "A futuristic metropolis with transportation through personal levitation devices",
    "A world where flora and fauna emit intricate patterns of sound as they interact",
    "A society that communicates through the arrangement of fallen leaves",
    "An ancient city with architecture influenced by the positions of constellations",
    "A realm of floating islands with waterfalls that flow upwards",
    "A city where inhabitants communicate through the manipulation of fire",
    "An underwater civilization with technology powered by harnessing underwater geysers",
    "A society that communicates through the patterns of migrating birds",
    "A realm where dreams and reality merge, creating a constantly shifting existence",
    "A city with architecture that adapts to the energy flows of the earth",
    "An ancient city hidden within the intricate network of an underground cave system",
    "A world where animals possess the ability to communicate with humans through images",
    "A society that communicates through the arrangement of sand dunes in the desert",
    "A realm where thoughts become visible as shimmering, colorful threads",
    "A city built on the back of a colossal, ancient bird-like creature",
    "An underwater realm with cities suspended within giant floating bubbles",
    "A futuristic metropolis with transportation through personal teleportation rings",
    "A world where flora and fauna emit intricate patterns of light as they interact",
    "A society that communicates through the arrangement of leaves on trees",
    "An ancient city with architecture influenced by the phases of the moons",
    "A realm of floating islands with rivers that flow in mid-air",
    "A city where inhabitants communicate through the movement of shadows",
    "An underwater civilization with technology powered by harnessing tidal forces",
    "A society that communicates through the patterns of migrating fish",
    "A realm where dreams shape the physical environment, creating a dream-like reality",
    "A city with architecture that responds to the vibrations of the earth",
    "An ancient city hidden within the labyrinthine tunnels of an ancient cave system",
    "A world where animals possess the ability to manipulate the growth of plants",
    "A society that communicates through the arrangement of clouds in the sky",
    "A realm where emotions and thoughts manifest as visible, swirling energy",
    "A city built on the back of a colossal, ancient serpent-like creature",
    "An underwater realm with cities nestled within intricate underwater caves",
    "A futuristic metropolis with transportation through personal levitation devices",
    "A world where flora and fauna emit intricate patterns of sound as they interact",
    "A society that communicates through the arrangement of fallen leaves",
    "An ancient city with architecture influenced by the positions of constellations",
    "A realm of floating islands with waterfalls that flow upwards",
    "A city where inhabitants communicate through the manipulation of fire",
    "An underwater civilization with technology powered by harnessing underwater geysers",
    "A society that communicates through the patterns of migrating birds",
    "A realm where dreams and reality merge, creating a constantly shifting existence",
    "A city with architecture that adapts to the energy flows of the earth",
    "An ancient city hidden within the intricate network of an underground cave system",
    "A world where animals possess the ability to communicate with humans through images",
    "A society that communicates through the arrangement of sand dunes in the desert",
    "A realm where thoughts become visible as shimmering, colorful threads",
    "A city built on the back of a colossal, ancient bird-like creature",
    "An underwater realm with cities suspended within giant floating bubbles",
    "A futuristic metropolis with transportation through personal teleportation rings",
    "A world where flora and fauna emit intricate patterns of light as they interact",
    "A society that communicates through the arrangement of leaves on trees",
    "An ancient city with architecture influenced by the phases of the moons",
    "A realm of floating islands with rivers that flow in mid-air",
    "A city where inhabitants communicate through the movement of shadows",
    "An underwater civilization with technology powered by harnessing tidal forces",
    "A society that communicates through the patterns of migrating fish",
    "A realm where dreams shape the physical environment, creating a dream-like reality",
    "A city with architecture that responds to the vibrations of the earth",
    "An ancient city hidden within the labyrinthine tunnels of an ancient cave system",
    "A world where animals possess the ability to manipulate the growth of plants",
    "A society that communicates through the arrangement of clouds in the sky",
    "A realm where emotions and thoughts manifest as visible, swirling energy",
    "A city built on the back of a colossal, ancient serpent-like creature",
    "An underwater realm with cities nestled within intricate underwater caves",
    "A futuristic metropolis with transportation through personal levitation devices",
    "A world where flora and fauna emit intricate patterns of sound as they interact",
    "A society that communicates through the arrangement of fallen leaves",
    "An ancient city with architecture influenced by the positions of constellations",
    "A realm of floating islands with waterfalls that flow upwards",
    "A city where inhabitants communicate through the manipulation of fire",
    "An underwater civilization with technology powered by harnessing underwater geysers",
    "A society that communicates through the patterns of migrating birds",
    "A realm where dreams and reality merge, creating a constantly shifting existence",
    "A city with architecture that adapts to the energy flows of the earth",
    "An ancient city hidden within the intricate network of an underground cave system",
    "A world where animals possess the ability to communicate with humans through images",
    "A society that communicates through the arrangement of sand dunes in the desert",
    "A realm where thoughts become visible as shimmering, colorful threads",
    "A city built on the back of a colossal, ancient bird-like creature",
    "An underwater realm with cities suspended within giant floating bubbles",
    "A futuristic metropolis with transportation through personal teleportation rings",
    "A world where flora and fauna emit intricate patterns of light as they interact",
    "A society that communicates through the arrangement of leaves on trees",
    "An ancient city with architecture influenced by the phases of the moons",
    "A realm of floating islands with rivers that flow in mid-air",
    "A city where inhabitants communicate through the movement of shadows",
    "An underwater civilization with technology powered by harnessing tidal forces",
    "A society that communicates through the patterns of migrating fish",
    "A realm where dreams shape the physical environment, creating a dream-like reality",
    "A city with architecture that responds to the vibrations of the earth",
    "An ancient city hidden within the labyrinthine tunnels of an ancient cave system",
    "A world where animals possess the ability to manipulate the growth of plants",
    "A society that communicates through the arrangement of clouds in the sky",
    "A realm where emotions and thoughts manifest as visible, swirling energy",
    "A city built on the back of a colossal, ancient serpent-like creature",
    "An underwater realm with cities nestled within intricate underwater caves",
    "A futuristic metropolis with transportation through personal levitation devices",
    "A world where flora and fauna emit intricate patterns of sound as they interact",
    "A society that communicates through the arrangement of fallen leaves",
    "An ancient city with architecture influenced by the positions of constellations",
    "A realm of floating islands with waterfalls that flow upwards",
    "A city where inhabitants communicate through the manipulation of fire",
    "An underwater civilization with technology powered by harnessing underwater geysers",
    "A society that communicates through the patterns of migrating birds",
    "A realm where dreams and reality merge, creating a constantly shifting existence",
    "A city with architecture that adapts to the energy flows of the earth",
    "An ancient city hidden within the intricate network of an underground cave system",
    "A world where animals possess the ability to communicate with humans through images",
    "A society that communicates through the arrangement of sand dunes in the desert",
    "A realm where thoughts become visible as shimmering, colorful threads",
    "Robot comforting a sobbing toaster, vacuum offers tissues",
    "Cats hosting 'Meowlympics' with odd sports"
  ];
  